<?php

use App\Http\Controllers\Api\V1\ActivityAttendeeController;
use App\Http\Controllers\Api\V1\ActivityController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BookingController;
use App\Http\Controllers\Api\V1\BudgetController;
use App\Http\Controllers\Api\V1\BudgetLineController;
use App\Http\Controllers\Api\V1\CircleController;
use App\Http\Controllers\Api\V1\ContributionController;
use App\Http\Controllers\Api\V1\DestinationProposalController;
use App\Http\Controllers\Api\V1\DeviceTokenController;
use App\Http\Controllers\Api\V1\EmergencyAlertController;
use App\Http\Controllers\Api\V1\EmergencyAlertRecipientController;
use App\Http\Controllers\Api\V1\ExchangeRateController;
use App\Http\Controllers\Api\V1\ExclusionRequestController;
use App\Http\Controllers\Api\V1\ExpenseController;
use App\Http\Controllers\Api\V1\ExpenseParticipantController;
use App\Http\Controllers\Api\V1\GroupActivityController;
use App\Http\Controllers\Api\V1\InvitationController;
use App\Http\Controllers\Api\V1\LocationPointController;
use App\Http\Controllers\Api\V1\LocationShareController;
use App\Http\Controllers\Api\V1\MeetingPointController;
use App\Http\Controllers\Api\V1\ModerationActionController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\NotificationPreferenceController;
use App\Http\Controllers\Api\V1\OfflineSyncQueueController;
use App\Http\Controllers\Api\V1\OutingController;
use App\Http\Controllers\Api\V1\PackingItemController;
use App\Http\Controllers\Api\V1\PartnerController;
use App\Http\Controllers\Api\V1\PhotoCommentController;
use App\Http\Controllers\Api\V1\PhotoController;
use App\Http\Controllers\Api\V1\PlaceController;
use App\Http\Controllers\Api\V1\PlanController;
use App\Http\Controllers\Api\V1\PollAnswerController;
use App\Http\Controllers\Api\V1\PollController;
use App\Http\Controllers\Api\V1\PollOptionController;
use App\Http\Controllers\Api\V1\PublicTripController;
use App\Http\Controllers\Api\V1\ReactionController;
use App\Http\Controllers\Api\V1\RecommendationController;
use App\Http\Controllers\Api\V1\ReminderController;
use App\Http\Controllers\Api\V1\ReportController;
use App\Http\Controllers\Api\V1\RouteSuggestionController;
use App\Http\Controllers\Api\V1\ServiceController;
use App\Http\Controllers\Api\V1\SettlementController;
use App\Http\Controllers\Api\V1\SubscriptionController;
use App\Http\Controllers\Api\V1\TripController;
use App\Http\Controllers\Api\V1\TripJournalEntryController;
use App\Http\Controllers\Api\V1\TripMemberController;
use App\Http\Controllers\Api\V1\TripPlaceController;
use App\Http\Controllers\Api\V1\TripRouteController;
use App\Http\Controllers\Api\V1\UserSessionController;
use App\Http\Controllers\TripNotificationController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->name('api.v1.')->middleware('throttle:api')->group(function (): void {
    Route::post('/auth/register', [AuthController::class, 'register'])->middleware('throttle:5,1')->name('auth.register');
    Route::post('/auth/login', [AuthController::class, 'login'])->middleware('throttle:5,1')->name('auth.login');
    Route::post('/auth/refresh', [AuthController::class, 'refresh'])->middleware('throttle:10,1')->name('auth.refresh');
    Route::post('/auth/email/verification/send', [AuthController::class, 'sendVerificationCode'])->middleware('throttle:5,1')->name('auth.email.verification.send');
    Route::post('/auth/email/verification/verify', [AuthController::class, 'verifyEmail'])->middleware('throttle:10,1')->name('auth.email.verification.verify');
    Route::post('/auth/password/forgot', [AuthController::class, 'forgotPassword'])->middleware('throttle:5,1')->name('auth.password.forgot');
    Route::post('/auth/password/reset', [AuthController::class, 'resetPassword'])->middleware('throttle:10,1')->name('auth.password.reset');
    Route::post('/auth/two-factor/verify', [AuthController::class, 'verifyTwoFactorLogin'])->middleware('throttle:10,1')->name('auth.two-factor.verify');

    Route::middleware(['auth:sanctum,api', 'jwt.version'])->group(function (): void {
        Route::get('/discover/trips', [PublicTripController::class, 'index'])->name('trips.discover');
        Route::get('/discover/trips/{id}', [PublicTripController::class, 'show'])->whereUuid('id')->name('trips.discover.show');
        Route::get('/me', [AuthController::class, 'me'])->name('me');
        Route::get('/me/sessions', [UserSessionController::class, 'current'])->name('me.sessions.index');
        Route::post('/me/sessions/revoke-others', [UserSessionController::class, 'revokeOthers'])->name('me.sessions.revoke-others');
        Route::patch('/me', [AuthController::class, 'updateProfile'])->name('profile.update');
        Route::put('/me/email', [AuthController::class, 'changeEmail'])->middleware('throttle:5,1')->name('profile.email.update');
        Route::post('/me/avatar', [AuthController::class, 'uploadAvatar'])->middleware('throttle:10,1')->name('profile.avatar.store');
        Route::delete('/me/avatar', [AuthController::class, 'deleteAvatar'])->name('profile.avatar.destroy');
        Route::delete('/auth/logout', [AuthController::class, 'logout'])->name('auth.logout');
        Route::put('/auth/password', [AuthController::class, 'changePassword'])->middleware('throttle:5,1')->name('auth.password.change');
        Route::post('/auth/two-factor/enable', [AuthController::class, 'enableTwoFactor'])->middleware('throttle:5,1')->name('auth.two-factor.enable');
        Route::post('/auth/two-factor/enable/verify', [AuthController::class, 'verifyTwoFactorEnable'])->middleware('throttle:10,1')->name('auth.two-factor.enable.verify');
        Route::delete('/auth/two-factor', [AuthController::class, 'disableTwoFactor'])->middleware('throttle:5,1')->name('auth.two-factor.disable');
        Route::apiResource('trips', TripController::class)->parameters(['trips' => 'id'])->whereUuid('id');
        Route::apiResource('circles', CircleController::class)->parameters(['circles' => 'id'])->whereUuid('id');
        Route::apiResource('outings', OutingController::class)->parameters(['outings' => 'id'])->whereUuid('id');
        Route::post('/outings/{id}/rsvp', [OutingController::class, 'respond'])->whereUuid('id')->name('outings.rsvp');
        Route::post('/outings/{id}/check-in', [OutingController::class, 'checkIn'])->whereUuid('id')->name('outings.check-in');
        Route::post('/outings/{id}/start', [OutingController::class, 'start'])->whereUuid('id')->name('outings.start');
        Route::post('/outings/{id}/finish', [OutingController::class, 'finish'])->whereUuid('id')->name('outings.finish');
        Route::post('/outings/{id}/contributions', [OutingController::class, 'contribute'])->whereUuid('id')->name('outings.contributions.store');
        Route::post('/outings/{id}/photos', [OutingController::class, 'addPhoto'])->whereUuid('id')->name('outings.photos.store');
        Route::patch('/outings/{id}/photos/{photoId}/story', [OutingController::class, 'toggleStory'])->whereUuid('id')->whereUuid('photoId')->name('outings.photos.story');
        Route::get('/group-activities', [GroupActivityController::class, 'index'])->name('group-activities.index');
        Route::post('/group-activities', [GroupActivityController::class, 'store'])->name('group-activities.store');
        Route::get('/trips/{trip}/route-plan', [TripRouteController::class, 'suggestOrder'])->whereUuid('trip')->name('trips.route-plan');
        Route::post('/trips/{trip}/notifications', [TripNotificationController::class, 'store'])->whereUuid('trip')->name('trips.notifications.store');
        Route::apiResource('trip-members', TripMemberController::class)->parameters(['trip-members' => 'id'])->whereUuid('id');
        Route::apiResource('trip-journal-entries', TripJournalEntryController::class)->parameters(['trip-journal-entries' => 'id'])->whereUuid('id');
        Route::apiResource('invitations', InvitationController::class)->parameters(['invitations' => 'id'])->whereUuid('id');
        Route::post('/invitations/respond', [InvitationController::class, 'respondByCode'])->middleware('throttle:10,1')->name('invitations.respond-by-code');
        Route::post('/invitations/{id}/respond', [InvitationController::class, 'respond'])->whereUuid('id')->name('invitations.respond');
        Route::apiResource('polls', PollController::class)->parameters(['polls' => 'id'])->whereUuid('id');
        Route::apiResource('poll-options', PollOptionController::class)->parameters(['poll-options' => 'id'])->whereUuid('id');
        Route::apiResource('poll-answers', PollAnswerController::class)->parameters(['poll-answers' => 'id'])->whereUuid('id');
        Route::apiResource('destination-proposals', DestinationProposalController::class)->parameters(['destination-proposals' => 'id'])->whereUuid('id');
        Route::apiResource('exclusion-requests', ExclusionRequestController::class)->parameters(['exclusion-requests' => 'id'])->whereUuid('id');
        Route::apiResource('reactions', ReactionController::class)->parameters(['reactions' => 'id'])->whereUuid('id');
        Route::get('/places/search', [PlaceController::class, 'search'])->middleware('throttle:expensive-api')->name('places.search');
        Route::get('/places/nearby', [PlaceController::class, 'nearby'])->middleware('throttle:expensive-api')->name('places.nearby');
        Route::get('/route-suggestions', [RouteSuggestionController::class, 'index'])->name('route-suggestions.index');
        Route::apiResource('places', PlaceController::class)->parameters(['places' => 'id'])->whereUuid('id');
        Route::apiResource('trip-places', TripPlaceController::class)->parameters(['trip-places' => 'id'])->whereUuid('id');
        Route::apiResource('activities', ActivityController::class)->parameters(['activities' => 'id'])->whereUuid('id');
        Route::apiResource('activity-attendees', ActivityAttendeeController::class)->parameters(['activity-attendees' => 'id'])->whereUuid('id');
        Route::apiResource('meeting-points', MeetingPointController::class)->parameters(['meeting-points' => 'id'])->whereUuid('id');
        Route::apiResource('reminders', ReminderController::class)->parameters(['reminders' => 'id'])->whereUuid('id');
        Route::apiResource('budgets', BudgetController::class)->parameters(['budgets' => 'id'])->whereUuid('id');
        Route::apiResource('budget-lines', BudgetLineController::class)->parameters(['budget-lines' => 'id'])->whereUuid('id');
        Route::apiResource('contributions', ContributionController::class)->parameters(['contributions' => 'id'])->whereUuid('id');
        Route::apiResource('expenses', ExpenseController::class)->parameters(['expenses' => 'id'])->whereUuid('id');
        Route::apiResource('expense-participants', ExpenseParticipantController::class)->parameters(['expense-participants' => 'id'])->whereUuid('id');
        Route::apiResource('settlements', SettlementController::class)->parameters(['settlements' => 'id'])->whereUuid('id');
        Route::apiResource('exchange-rates', ExchangeRateController::class)->parameters(['exchange-rates' => 'id'])->whereUuid('id');
        Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
        Route::post('/notifications/read-all', [NotificationController::class, 'markAllRead'])->name('notifications.read-all');
        Route::get('/notifications/{id}', [NotificationController::class, 'show'])->whereUuid('id')->name('notifications.show');
        Route::patch('/notifications/{id}/read', [NotificationController::class, 'markRead'])->whereUuid('id')->name('notifications.read');
        Route::delete('/notifications/{id}', [NotificationController::class, 'destroy'])->whereUuid('id')->name('notifications.destroy');
        Route::apiResource('notification-preferences', NotificationPreferenceController::class)->parameters(['notification-preferences' => 'id'])->whereUuid('id');
        Route::apiResource('device-tokens', DeviceTokenController::class)->parameters(['device-tokens' => 'id'])->whereUuid('id');
        Route::apiResource('photos', PhotoController::class)->parameters(['photos' => 'id'])->whereUuid('id');
        Route::apiResource('photo-comments', PhotoCommentController::class)->parameters(['photo-comments' => 'id'])->whereUuid('id');
        Route::apiResource('location-shares', LocationShareController::class)->parameters(['location-shares' => 'id'])->whereUuid('id');
        Route::apiResource('location-points', LocationPointController::class)->parameters(['location-points' => 'id'])->whereUuid('id');
        Route::apiResource('emergency-alerts', EmergencyAlertController::class)->parameters(['emergency-alerts' => 'id'])->whereUuid('id');
        Route::apiResource('emergency-alert-recipients', EmergencyAlertRecipientController::class)->parameters(['emergency-alert-recipients' => 'id'])->whereUuid('id');
        Route::apiResource('reports', ReportController::class)->parameters(['reports' => 'id'])->whereUuid('id');
        Route::apiResource('moderation-actions', ModerationActionController::class)->parameters(['moderation-actions' => 'id'])->whereUuid('id');
        Route::apiResource('offline-sync-queue', OfflineSyncQueueController::class)->parameters(['offline-sync-queue' => 'id'])->whereUuid('id');
        Route::apiResource('packing-items', PackingItemController::class)->parameters(['packing-items' => 'id'])->whereUuid('id');
        Route::apiResource('plans', PlanController::class)->parameters(['plans' => 'id'])->whereUuid('id');
        Route::apiResource('subscriptions', SubscriptionController::class)->parameters(['subscriptions' => 'id'])->whereUuid('id');
        Route::apiResource('partners', PartnerController::class)->parameters(['partners' => 'id'])->whereUuid('id');
        Route::apiResource('services', ServiceController::class)->parameters(['services' => 'id'])->whereUuid('id');
        Route::apiResource('bookings', BookingController::class)->parameters(['bookings' => 'id'])->whereUuid('id');
        Route::apiResource('recommendations', RecommendationController::class)->parameters(['recommendations' => 'id'])->whereUuid('id');
    });
});
